version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      PORT: "8000"
      MESSAGE_BUS: "amqp://rabbitmq"
    command: "php -S 0.0.0.0:8000 -t public/"
    links:
      - mysql
      - rabbitmq
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "todo"
      MYSQL_ROOT_PASSWORD: "root"
  rabbitmq:
    container_name: rabbitmq-management
    image: rabbitmq:3-management