version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      PORT: "8000"
      MESSAGE_BUS: "amqp://rabbitmq"
      TASK_CREATED: "task_created_ex"
      TASK_COMPLETED: "task_completed_ex"
      TASK_REOPENED: "task_reopened_ex"
      TASK_EDITED: "task_edited_ex"
      TASK_DELETED: "task_deleted_ex"
    command: "php -S 0.0.0.0:8000 -t public/"
    links:
      - mysql
      - rabbitmq
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "todo"
      MYSQL_ROOT_PASSWORD: "root"
  rabbitmq:
    container_name: rabbitmq-management
    image: rabbitmq:3-management
    ports:
    - "15672:15672"