App\Todo\Domain\Task:
  type: entity
  table: tasks
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
    status:
      type: status
      nullable: false
    dueDate:
      type: datetime
      nullable: true,
      column: due_date
    createdAt:
      type: datetime
      nullable: true
      options:
        default: CURRENT_TIMESTAMP
      column: created_at
    updatedAt:
      type: datetime
      nullable: true
      options:
        default: CURRENT_TIMESTAMP
      column: updated_at